title: Andrew's Portfolio
author: Andrew Patipaksiri
email: apax714@gmail.com
description: portfolio & all things programming
github_username:  apati04

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
